word_1 = set(input('Введите первое слово: '))
word_2 = set(input('Введите второе слово: '))
word_intersection = word_1.intersection(word_2)
print('Буквы из обоих слов: ', *word_intersection)
word_just_1 = word_1.difference(word_2)
print('Буквы только из первого слова:', *word_just_1, sep=' ')
word_just_2 = word_2.difference(word_1)
print('Буквы только из второго слова:', *word_just_2, sep=' ')
word_union = word_1.union(word_2)
print('Буквы из всех слов', *word_union, sep=' ')
